@startuml domaindiagram
object Main
object Game
object Tiles
object Board
object Player
object Letter

Main *-- Game
Game o-- Player
Game *-- Board 
Game *-- Letter
Player o-- Letter
Board *-- Tiles
Board o-- Letter

@enduml