@startuml
object Main
object Game
object Tiles
object Board
object Player
object Letter

Main *-- Game
Game o-- Player
Game *-- Board 
Game *-- Letters
Player o-- Letters
Board *-- Tiles
Board o-- Letter

@enduml